name: flutter_house_reservation
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  loading_animation_widget: ^1.2.1
  carousel_slider: ^4.2.1
  flutter_otp_text_field: ^1.1.3+2
  flutter_screenutil: ^5.9.1
  card_swiper: ^3.0.1
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/pngs/
    - assets/svgs/
    - assets/jpgs/


  fonts:
    - family: yekanBakh
      fonts:
        - asset: assets/fonts/YekanBakh-Bold.ttf
          weight: 700
        - asset: assets/fonts/YekanBakh-Heavy.ttf
          weight: 900
        - asset: assets/fonts/YekanBakh-Medium.ttf
          weight: 500

