class AppStrings {
  AppStrings._();
  static const appVersion = 'ورژن : 1.0.0';
  static const appName = 'Rentee';
  static const sendComment = 'ثبت نظر';
  static const next = 'بعدی';
  static const reservationNow = 'همین حالا رزرو کن!';
  static const comments = 'نظرات';
  static const showComments = 'مشاهده نظرات';
  static const inputPhoneHint = 'شماره تماس...';
  static const inputCommentHint = 'خوشحال میشیم نظرت رو با ما و بقیه دوستات به اشتراک بزاری!';
  static const searchHint = 'متن جست و جو را وارد کنید...';
  static const phoneNumberLabel = 'شماره همراه';
  static const fullNameLabel = 'نام و نام خانوادگی';
  static const usernameLabel = 'نام کاربری';
  static const sendOtpCode = 'ارسال کد';
  static const description = 'توضیحات';
  static const facilities = 'امکانات';
  static const acceptOtpCode = 'تایید کد';
  static const inputAcceptOtpCode = 'کد ارسال شده را وارد کنید';
  static const inputOtpCodeMessage = 'لطفا کد تایید ارسال شده را وارد کنید.';
  static const resendCodeMessage = 'ارسال مجدد در: ';
  static const resendCode = 'ارسال مجدد ';
  static const lestGo = 'بزن بریم!';
  static const previous = 'قبلی';
  static const register = 'ثبت نام';
  static const signIn = 'ورود';
  static const suggestionForYou = 'ییشنهادات برای شما';
  static const popularHouse = 'محبوبترین ها';
  static const sendSmsMessage = 'لظفا شماره تلفن خود را جهت دریافت کد تایید وارد کنید.';
  static const registerMessage = 'در صورت تمایل اطلاعات کاربری خود را تکمیل کنید';
  static const sendOtpTitle = 'ارسال کد ورود';
}